---
- name: Start a Morpheus Dev Environment
  hosts: localhost
  tasks:
  - name: mysql container
    community.docker.docker_container:
      name: mysqldb
      image: mysql
      state: absent
      force_kill: true
  - name: adminer
    community.docker.docker_container:
      name: adminer
      image: adminer
      state: absent
      force_kill: true
  - name: rabbit container
    community.docker.docker_container:
      name: rabbitmq
      image: "rabbitmq:3-management"
      state: absent
      force_kill: true
  - name: Elastic Container
    community.docker.docker_container:
      name: elasticsearch
      image: "elasticsearch:7.17.18"
      state: absent
      force_kill: true   
