---
- name: Install nginx in a python docker container
  hosts: all
  #become: true
  #gather_facts: true
  tasks:
  - name: Install nginx via apt
    ansible.builtin.apt:
      update_cache: true
      pkg:
      - nginx
  - name: Installing Template site
    ansible.builtin.template:
      src: template/nginx-site.html.j2
      dest: /var/www/html/index.html
      force: true
    notify:
      - Restart nginx

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
