---
- name: Install nginx in a python docker container
  hosts: all
  become: true
  gather_facts: true
  tasks:
  - name: "install nginx"
      ansible.builtin.apt:
        update_cache: true
        pkg:
        - nginx
