---
- name: Install nginx in a python docker container
  hosts: all
  #become: true
  #gather_facts: true
  tasks:
  - name: Install nginx via apt
    ansible.builtin.apt:
      update_cache: true
      pkg:
      - nginx
  - name: Start nginx service
    ansible.builtin.service:
      name: nginx
      state: started
