---
- name: Stop a bunch of containers
  hosts: localhost
  tasks:
  - name: "Stop and destroy ansible-n containers"
    community.docker.docker_container:
      name: "ansible-{{ item }}"
      image: python
      tty: true
      interactive: true
      state: absent
      force_kill: true
    loop: "{{ range(1,6) }}"
  - name: "Stop and destroy Nginx container"
    community.docker.docker_container:
      name: "nginx-1"
      state: absent
      force_kill: true
