---
- name: Start a bunch of containers
  hosts: localhost
  tasks:
  - community.docker.docker_container:
      name: "ansible-{{ item }}"
      image: python
      # keep the containers running in the background
      tty: true
      interactive: true
      state: absent
      force_kill: true
    loop: "{{ range(1,6) }}"
