---
- name: Debug Info
  hosts: all
  gather_facts: false
  tasks:
    - name: Debug hostvars
      debug:
        msg: "User {{ ansible_user }} on host {{ inventory_hostname }} - connection {{ ansible_connection }}"

