---
- name: Testing Playbooks
  hosts: all
  gather_facts: false
  tasks:
  - name: Print Lease Token
    ansible.builtin.debug:
      msg:
      - "Execution lease for this play is {{ ansible_morpheus_token }}"
      - "The Morpheus Appliance is {{ ansible_morpheus_url}}"
      - "The containerId is {{ ansible_morpheus_container_id}}"
  - name: Ansible tmp folder
    ansible.builtin.shell: echo "This is user $USER - pwd $PWD"
  - name: Make an Execution Request
    ansible.builtin.uri:
      url: "{{ ansible_morpheus_url }}/api/execution-request/lease/{{ ansible_morpheus_token }}?containerId={{ ansible_morpheus_container_id }}"
      method: POST
      body_format: json
      body: {"cmd":"hsotnamectl"}
      return_content: true
    register: this
  - ansible.builtin.debug:
      var: {{ this }}

